all: tempo tempopush

tempo: tempo.o tempo1.o tempo2.o tempo3.o tempo4.o smpl.o rand.o
	$(LINK.c) -o tempo -Bstatic tempo.o smpl.o rand.o -lm
	$(LINK.c) -o tempo1 -Bstatic tempo1.o smpl.o rand.o -lm
	$(LINK.c) -o tempo2 -Bstatic tempo2.o smpl.o rand.o -lm
	$(LINK.c) -o tempo3 -Bstatic tempo3.o smpl.o rand.o -lm
	$(LINK.c) -o tempo4 -Bstatic tempo4.o smpl.o rand.o -lm

tempopush: tempopush2.o smpl.o rand.o
	$(LINK.c) -o $@ -Bstatic tempopush2.o smpl.o rand.o -lm

*.o:
	$(COMPILE.c) -g *.o

clean:
	$(RM) *.o tempo tempo1 tempo2 tempo3 tempo4 tempopush relat saida
